### ISSUE TITLE
Option -p not recognized

### ISSUE THREAD

**Issue by advorzhak** [farrokhi/dnsdiag#106]
```zsh
# dnseval -v -f serverList.txt -c 100000 -t A -p 5335 www.linkedin.com
option -p not recognized
dnseval version 2.1.0

usage: dnseval [-ehmvCTXH] [-f server-list] [-j output.json] [-c count] [-t type] [-p port] [-w wait] hostname
  -h  --help        Show this help
  -f  --file        DNS server list to use (default: system resolvers)
  -c  --count       Number of requests to send (default: 10)
  -m  --cache-miss  Force cache miss measurement by prepending a random hostname
  -w  --wait        Maximum wait time for a reply (default: 2)
  -t  --type        DNS request record type (default: A)
  -T  --tcp         Use TCP instead of UDP
  -X  --tls         Use TLS as transport protocol
  -j  --json        Save results as a JSON formatted file
  -H  --doh         Use HTTPS as transport protols (DoH)
  -p  --port        DNS server port number (default: 53 for TCP/UDP and 853 for TLS)
  -S  --srcip       Query source IP address
  -e  --edns        Disable EDNS0 (default: Enabled)
  -D  --dnssec      Enable 'DNSSEC desired' flag in requests.
  -C  --color       Print colorful output
  -v  --verbose     Print actual dns response
```

**Comment by zhraa1992** [comment]
# dnseval -v -f serverList.txt -c 100000 -t A -p 5335 www.linkedin.com
option -p not recognized
dnseval version 2.1.0

usage: dnseval [-ehmvCTXH] [-f server-list] [-j output.json] [-c count] [-t type] [-p port] [-w wait] hostname
  -h  --help        Show this help
  -f  --file        DNS server list to use (default: system resolvers)
  -c  --count       Number of requests to send (default: 10)
  -m  --cache-miss  Force cache miss measurement by prepending a random hostname
  -w  --wait        Maximum wait time for a reply (default: 2)
  -t  --type        DNS request record type (default: A)
  -T  --tcp         Use TCP instead of UDP
  -X  --tls         Use TLS as transport protocol
  -j  --json        Save results as a JSON formatted file
  -H  --doh         Use HTTPS as transport protols (DoH)
  -p  --port        DNS server port number (default: 53 for TCP/UDP and 853 for TLS)
  -S  --srcip       Query source IP address
  -e  --edns        Disable EDNS0 (default: Enabled)
  -D  --dnssec      Enable 'DNSSEC desired' flag in requests.
  -C  --color       Print colorful output
  -v  --verbose     Print actual dns response

**Comment by advorzhak** [comment]
Hi, @farrokhi 

Thanks for fixing this issue.

BR, Andrii
